language: objective-c
osx_image: xcode8
env: # Specify two projects here, so that each is run using the `script` specified below
  - PROJECT_DIR=SampleProject
  - PROJECT_DIR=SwiftSampleProject
  - PROJECT_DIR="Paging Data Source Example"
script: cd $PROJECT_DIR && bundle exec fastlane test
after_script:
  - pod lib lint
git:
  depth: 10000  # For the auto-incrementing build number script to work, we need to clone with a basically-infinite depth.
cache:
  - bundler  # After main-repo builds, save the "bundler" (local Ruby gems) stuff to cache for future builds.
