language: objective-c
osx_image: xcode8
script:
  - cd SampleProject && bundle exec fastlane test
  - cd ../SwiftSampleProject && bundle exec fastlane test
after_script:
  - pod lib lint
git:
  depth: 10000  # For the auto-incrementing build number script to work, we need to clone with a basically-infinite depth.
cache:
  - bundler  # After main-repo builds, save the "bundler" (local Ruby gems) stuff to cache for future builds.
